version: 2.1

orbs:
  cypress: cypress-io/cypress@1.8.0

jobs:
  validate:
    executor: cypress/base-10
    steps:
      - attach_workspace:
          at: ~/
      - run: yarn validate
  release:
    executor: cypress/base-10
    steps:
      - attach_workspace:
          at: ~/
      - run: yarn semantic-release

workflows:
  build:
    jobs:
      - cypress/run:
          yarn: true
          start: yarn develop
          wait-on: '--timeout 40000 http://localhost:8000'
      - validate:
          requires:
            - cypress/run
      - release:
          requires:
            - validate
          filters:
            branches:
              only: master
